// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: node.proto

package pb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// NodeType is an enum of possible node types
type NodeType int32

const (
	NodeType_INVALID   NodeType = 0
	NodeType_SATELLITE NodeType = 1
	NodeType_STORAGE   NodeType = 2
	NodeType_UPLINK    NodeType = 3
	NodeType_BOOTSTRAP NodeType = 4
)

var NodeType_name = map[int32]string{
	0: "INVALID",
	1: "SATELLITE",
	2: "STORAGE",
	3: "UPLINK",
	4: "BOOTSTRAP",
}

var NodeType_value = map[string]int32{
	"INVALID":   0,
	"SATELLITE": 1,
	"STORAGE":   2,
	"UPLINK":    3,
	"BOOTSTRAP": 4,
}

func (x NodeType) String() string {
	return proto.EnumName(NodeType_name, int32(x))
}

func (NodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

// NodeTransport is an enum of possible transports for the overlay network
type NodeTransport int32

const (
	NodeTransport_TCP_TLS_GRPC NodeTransport = 0
)

var NodeTransport_name = map[int32]string{
	0: "TCP_TLS_GRPC",
}

var NodeTransport_value = map[string]int32{
	"TCP_TLS_GRPC": 0,
}

func (x NodeTransport) String() string {
	return proto.EnumName(NodeTransport_name, int32(x))
}

func (NodeTransport) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{1}
}

// TODO move statdb.Update() stuff out of here
// Node represents a node in the overlay network
// Node is info for a updating a single storagenode, used in the Update rpc calls
type Node struct {
	Id                   NodeID       `protobuf:"bytes,1,opt,name=id,proto3,customtype=NodeID" json:"id"`
	Address              *NodeAddress `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Paddress             *NodeAddress `protobuf:"bytes,14,opt,name=paddress,proto3" json:"paddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetAddress() *NodeAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Node) GetPaddress() *NodeAddress {
	if m != nil {
		return m.Paddress
	}
	return nil
}

// NodeAddress contains the information needed to communicate with a node on the network
type NodeAddress struct {
	Transport            NodeTransport `protobuf:"varint,1,opt,name=transport,proto3,enum=node.NodeTransport" json:"transport,omitempty"`
	Address              string        `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NodeAddress) Reset()         { *m = NodeAddress{} }
func (m *NodeAddress) String() string { return proto.CompactTextString(m) }
func (*NodeAddress) ProtoMessage()    {}
func (*NodeAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{1}
}
func (m *NodeAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeAddress.Unmarshal(m, b)
}
func (m *NodeAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeAddress.Marshal(b, m, deterministic)
}
func (m *NodeAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeAddress.Merge(m, src)
}
func (m *NodeAddress) XXX_Size() int {
	return xxx_messageInfo_NodeAddress.Size(m)
}
func (m *NodeAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeAddress.DiscardUnknown(m)
}

var xxx_messageInfo_NodeAddress proto.InternalMessageInfo

func (m *NodeAddress) GetTransport() NodeTransport {
	if m != nil {
		return m.Transport
	}
	return NodeTransport_TCP_TLS_GRPC
}

func (m *NodeAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// NodeStats is the reputation characteristics of a node
type NodeStats struct {
	NodeId               NodeID               `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3,customtype=NodeID" json:"node_id"`
	Latency_90           int64                `protobuf:"varint,2,opt,name=latency_90,json=latency90,proto3" json:"latency_90,omitempty"`
	AuditSuccessRatio    float64              `protobuf:"fixed64,3,opt,name=audit_success_ratio,json=auditSuccessRatio,proto3" json:"audit_success_ratio,omitempty"`
	UptimeRatio          float64              `protobuf:"fixed64,4,opt,name=uptime_ratio,json=uptimeRatio,proto3" json:"uptime_ratio,omitempty"`
	AuditCount           int64                `protobuf:"varint,5,opt,name=audit_count,json=auditCount,proto3" json:"audit_count,omitempty"`
	AuditSuccessCount    int64                `protobuf:"varint,6,opt,name=audit_success_count,json=auditSuccessCount,proto3" json:"audit_success_count,omitempty"`
	UptimeCount          int64                `protobuf:"varint,7,opt,name=uptime_count,json=uptimeCount,proto3" json:"uptime_count,omitempty"`
	UptimeSuccessCount   int64                `protobuf:"varint,8,opt,name=uptime_success_count,json=uptimeSuccessCount,proto3" json:"uptime_success_count,omitempty"`
	LastContactSuccess   *timestamp.Timestamp `protobuf:"bytes,9,opt,name=last_contact_success,json=lastContactSuccess,proto3" json:"last_contact_success,omitempty"`
	LastContactFailure   *timestamp.Timestamp `protobuf:"bytes,10,opt,name=last_contact_failure,json=lastContactFailure,proto3" json:"last_contact_failure,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NodeStats) Reset()         { *m = NodeStats{} }
func (m *NodeStats) String() string { return proto.CompactTextString(m) }
func (*NodeStats) ProtoMessage()    {}
func (*NodeStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{2}
}
func (m *NodeStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeStats.Unmarshal(m, b)
}
func (m *NodeStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeStats.Marshal(b, m, deterministic)
}
func (m *NodeStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeStats.Merge(m, src)
}
func (m *NodeStats) XXX_Size() int {
	return xxx_messageInfo_NodeStats.Size(m)
}
func (m *NodeStats) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeStats.DiscardUnknown(m)
}

var xxx_messageInfo_NodeStats proto.InternalMessageInfo

func (m *NodeStats) GetLatency_90() int64 {
	if m != nil {
		return m.Latency_90
	}
	return 0
}

func (m *NodeStats) GetAuditSuccessRatio() float64 {
	if m != nil {
		return m.AuditSuccessRatio
	}
	return 0
}

func (m *NodeStats) GetUptimeRatio() float64 {
	if m != nil {
		return m.UptimeRatio
	}
	return 0
}

func (m *NodeStats) GetAuditCount() int64 {
	if m != nil {
		return m.AuditCount
	}
	return 0
}

func (m *NodeStats) GetAuditSuccessCount() int64 {
	if m != nil {
		return m.AuditSuccessCount
	}
	return 0
}

func (m *NodeStats) GetUptimeCount() int64 {
	if m != nil {
		return m.UptimeCount
	}
	return 0
}

func (m *NodeStats) GetUptimeSuccessCount() int64 {
	if m != nil {
		return m.UptimeSuccessCount
	}
	return 0
}

func (m *NodeStats) GetLastContactSuccess() *timestamp.Timestamp {
	if m != nil {
		return m.LastContactSuccess
	}
	return nil
}

func (m *NodeStats) GetLastContactFailure() *timestamp.Timestamp {
	if m != nil {
		return m.LastContactFailure
	}
	return nil
}

// NodeOperator contains info about the storage node operator
type NodeOperator struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Wallet               string   `protobuf:"bytes,2,opt,name=wallet,proto3" json:"wallet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeOperator) Reset()         { *m = NodeOperator{} }
func (m *NodeOperator) String() string { return proto.CompactTextString(m) }
func (*NodeOperator) ProtoMessage()    {}
func (*NodeOperator) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{3}
}
func (m *NodeOperator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeOperator.Unmarshal(m, b)
}
func (m *NodeOperator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeOperator.Marshal(b, m, deterministic)
}
func (m *NodeOperator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeOperator.Merge(m, src)
}
func (m *NodeOperator) XXX_Size() int {
	return xxx_messageInfo_NodeOperator.Size(m)
}
func (m *NodeOperator) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeOperator.DiscardUnknown(m)
}

var xxx_messageInfo_NodeOperator proto.InternalMessageInfo

func (m *NodeOperator) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NodeOperator) GetWallet() string {
	if m != nil {
		return m.Wallet
	}
	return ""
}

// NodeCapacity contains all relevant data about a nodes ability to store data
type NodeCapacity struct {
	FreeBandwidth        int64    `protobuf:"varint,1,opt,name=free_bandwidth,json=freeBandwidth,proto3" json:"free_bandwidth,omitempty"`
	FreeDisk             int64    `protobuf:"varint,2,opt,name=free_disk,json=freeDisk,proto3" json:"free_disk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeCapacity) Reset()         { *m = NodeCapacity{} }
func (m *NodeCapacity) String() string { return proto.CompactTextString(m) }
func (*NodeCapacity) ProtoMessage()    {}
func (*NodeCapacity) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{4}
}
func (m *NodeCapacity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeCapacity.Unmarshal(m, b)
}
func (m *NodeCapacity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeCapacity.Marshal(b, m, deterministic)
}
func (m *NodeCapacity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeCapacity.Merge(m, src)
}
func (m *NodeCapacity) XXX_Size() int {
	return xxx_messageInfo_NodeCapacity.Size(m)
}
func (m *NodeCapacity) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeCapacity.DiscardUnknown(m)
}

var xxx_messageInfo_NodeCapacity proto.InternalMessageInfo

func (m *NodeCapacity) GetFreeBandwidth() int64 {
	if m != nil {
		return m.FreeBandwidth
	}
	return 0
}

func (m *NodeCapacity) GetFreeDisk() int64 {
	if m != nil {
		return m.FreeDisk
	}
	return 0
}

// Deprecated: use NodeOperator instead
type NodeMetadata struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Wallet               string   `protobuf:"bytes,2,opt,name=wallet,proto3" json:"wallet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeMetadata) Reset()         { *m = NodeMetadata{} }
func (m *NodeMetadata) String() string { return proto.CompactTextString(m) }
func (*NodeMetadata) ProtoMessage()    {}
func (*NodeMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{5}
}
func (m *NodeMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeMetadata.Unmarshal(m, b)
}
func (m *NodeMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeMetadata.Marshal(b, m, deterministic)
}
func (m *NodeMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeMetadata.Merge(m, src)
}
func (m *NodeMetadata) XXX_Size() int {
	return xxx_messageInfo_NodeMetadata.Size(m)
}
func (m *NodeMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_NodeMetadata proto.InternalMessageInfo

func (m *NodeMetadata) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NodeMetadata) GetWallet() string {
	if m != nil {
		return m.Wallet
	}
	return ""
}

// Deprecated: use NodeCapacity instead
type NodeRestrictions struct {
	FreeBandwidth        int64    `protobuf:"varint,1,opt,name=free_bandwidth,json=freeBandwidth,proto3" json:"free_bandwidth,omitempty"`
	FreeDisk             int64    `protobuf:"varint,2,opt,name=free_disk,json=freeDisk,proto3" json:"free_disk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeRestrictions) Reset()         { *m = NodeRestrictions{} }
func (m *NodeRestrictions) String() string { return proto.CompactTextString(m) }
func (*NodeRestrictions) ProtoMessage()    {}
func (*NodeRestrictions) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{6}
}
func (m *NodeRestrictions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeRestrictions.Unmarshal(m, b)
}
func (m *NodeRestrictions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeRestrictions.Marshal(b, m, deterministic)
}
func (m *NodeRestrictions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeRestrictions.Merge(m, src)
}
func (m *NodeRestrictions) XXX_Size() int {
	return xxx_messageInfo_NodeRestrictions.Size(m)
}
func (m *NodeRestrictions) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeRestrictions.DiscardUnknown(m)
}

var xxx_messageInfo_NodeRestrictions proto.InternalMessageInfo

func (m *NodeRestrictions) GetFreeBandwidth() int64 {
	if m != nil {
		return m.FreeBandwidth
	}
	return 0
}

func (m *NodeRestrictions) GetFreeDisk() int64 {
	if m != nil {
		return m.FreeDisk
	}
	return 0
}

// NodeVersion contains
type NodeVersion struct {
	Version              string               `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	CommitHash           string               `protobuf:"bytes,2,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Release              bool                 `protobuf:"varint,4,opt,name=release,proto3" json:"release,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NodeVersion) Reset()         { *m = NodeVersion{} }
func (m *NodeVersion) String() string { return proto.CompactTextString(m) }
func (*NodeVersion) ProtoMessage()    {}
func (*NodeVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{7}
}
func (m *NodeVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeVersion.Unmarshal(m, b)
}
func (m *NodeVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeVersion.Marshal(b, m, deterministic)
}
func (m *NodeVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeVersion.Merge(m, src)
}
func (m *NodeVersion) XXX_Size() int {
	return xxx_messageInfo_NodeVersion.Size(m)
}
func (m *NodeVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeVersion.DiscardUnknown(m)
}

var xxx_messageInfo_NodeVersion proto.InternalMessageInfo

func (m *NodeVersion) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *NodeVersion) GetCommitHash() string {
	if m != nil {
		return m.CommitHash
	}
	return ""
}

func (m *NodeVersion) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *NodeVersion) GetRelease() bool {
	if m != nil {
		return m.Release
	}
	return false
}

func init() {
	proto.RegisterEnum("node.NodeType", NodeType_name, NodeType_value)
	proto.RegisterEnum("node.NodeTransport", NodeTransport_name, NodeTransport_value)
	proto.RegisterType((*Node)(nil), "node.Node")
	proto.RegisterType((*NodeAddress)(nil), "node.NodeAddress")
	proto.RegisterType((*NodeStats)(nil), "node.NodeStats")
	proto.RegisterType((*NodeOperator)(nil), "node.NodeOperator")
	proto.RegisterType((*NodeCapacity)(nil), "node.NodeCapacity")
	proto.RegisterType((*NodeMetadata)(nil), "node.NodeMetadata")
	proto.RegisterType((*NodeRestrictions)(nil), "node.NodeRestrictions")
	proto.RegisterType((*NodeVersion)(nil), "node.NodeVersion")
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_0c843d59d2d938e7) }

var fileDescriptor_0c843d59d2d938e7 = []byte{
	// 733 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcd, 0x6e, 0xea, 0x46,
	0x14, 0xc7, 0xc3, 0x47, 0x00, 0x1f, 0x3e, 0xe4, 0x4c, 0x50, 0x85, 0x52, 0xb5, 0x24, 0x48, 0x55,
	0xa3, 0x54, 0x25, 0x69, 0xba, 0x69, 0xa4, 0x6e, 0x80, 0xa4, 0x29, 0x2d, 0x05, 0x34, 0xb8, 0x59,
	0x64, 0x63, 0x0d, 0xf6, 0x04, 0x46, 0x31, 0xb6, 0xe5, 0x19, 0x37, 0xe2, 0x3d, 0xba, 0xec, 0x03,
	0xf5, 0x19, 0xee, 0x22, 0xeb, 0xfb, 0x18, 0x57, 0xf3, 0x61, 0x08, 0x8a, 0x72, 0xa5, 0x48, 0x77,
	0xe7, 0x73, 0xce, 0xef, 0x7c, 0xcc, 0x99, 0xf9, 0x1b, 0x20, 0x8c, 0x7c, 0xda, 0x8d, 0x93, 0x48,
	0x44, 0xa8, 0x28, 0xbf, 0x8f, 0x60, 0x11, 0x2d, 0x22, 0xed, 0x39, 0x6a, 0x2f, 0xa2, 0x68, 0x11,
	0xd0, 0x73, 0x65, 0xcd, 0xd3, 0x87, 0x73, 0xc1, 0x56, 0x94, 0x0b, 0xb2, 0x8a, 0x35, 0xd0, 0xf9,
	0x37, 0x0f, 0xc5, 0x71, 0xe4, 0x53, 0xf4, 0x2d, 0xe4, 0x99, 0xdf, 0xca, 0x1d, 0xe7, 0x4e, 0x6b,
	0xfd, 0xc6, 0xff, 0xcf, 0xed, 0xbd, 0x0f, 0xcf, 0xed, 0x92, 0x8c, 0x0c, 0xaf, 0x71, 0x9e, 0xf9,
	0xe8, 0x07, 0x28, 0x13, 0xdf, 0x4f, 0x28, 0xe7, 0xad, 0xfc, 0x71, 0xee, 0xb4, 0x7a, 0x79, 0xd0,
	0x55, 0x9d, 0x25, 0xd2, 0xd3, 0x01, 0x9c, 0x11, 0xe8, 0x47, 0xa8, 0xc4, 0x19, 0xdd, 0x78, 0x8b,
	0xde, 0x20, 0x7f, 0x14, 0x2b, 0x05, 0xbb, 0x81, 0x8b, 0x62, 0x1d, 0x53, 0x5c, 0x4b, 0x28, 0x17,
	0x09, 0xf3, 0x04, 0x8b, 0x42, 0x8e, 0x21, 0xa1, 0x71, 0x2a, 0x88, 0x34, 0x70, 0x65, 0x45, 0x05,
	0xf1, 0x89, 0x20, 0xb8, 0x16, 0x10, 0x41, 0x43, 0x6f, 0xed, 0x06, 0x8c, 0x0b, 0x5c, 0x27, 0xa9,
	0xcf, 0x84, 0xcb, 0x53, 0xcf, 0x93, 0x65, 0xf7, 0x19, 0x77, 0xd3, 0x18, 0x37, 0xd2, 0xd8, 0x27,
	0x82, 0xba, 0x06, 0xc5, 0x4d, 0x63, 0xef, 0xc2, 0x75, 0xe3, 0x4d, 0x63, 0xb9, 0x18, 0x5c, 0xfe,
	0x87, 0x26, 0x9c, 0x45, 0x61, 0xe7, 0x1e, 0xaa, 0x2f, 0x46, 0x45, 0x3f, 0x81, 0x25, 0x12, 0x12,
	0xf2, 0x38, 0x4a, 0x84, 0xda, 0x51, 0xe3, 0xf2, 0x70, 0x7b, 0x20, 0x27, 0x0b, 0xe1, 0x2d, 0x85,
	0x5a, 0xbb, 0xfb, 0xb2, 0x36, 0xcb, 0xe9, 0x7c, 0x2c, 0x80, 0x25, 0xd3, 0x66, 0x82, 0x08, 0x8e,
	0xbe, 0x87, 0xb2, 0x2c, 0xe4, 0xbe, 0xb9, 0xfc, 0x92, 0x0c, 0x0f, 0x7d, 0xf4, 0x0d, 0x40, 0x76,
	0xec, 0xab, 0x0b, 0x55, 0xb3, 0x80, 0x2d, 0xe3, 0xb9, 0xba, 0x40, 0x5d, 0x38, 0xdc, 0x39, 0x9a,
	0x9b, 0xc8, 0xad, 0xb5, 0x0a, 0xc7, 0xb9, 0xd3, 0x1c, 0x3e, 0x50, 0xa1, 0x99, 0x39, 0xb4, 0x0c,
	0xa0, 0x13, 0xa8, 0xe9, 0x43, 0x1b, 0xb0, 0xa8, 0xc0, 0xaa, 0x59, 0x84, 0x42, 0xda, 0x50, 0xd5,
	0x25, 0xbd, 0x28, 0x0d, 0x45, 0x6b, 0x5f, 0xb5, 0x04, 0xe5, 0x1a, 0x48, 0xcf, 0xeb, 0x9e, 0x1a,
	0x2c, 0x29, 0x70, 0xa7, 0xa7, 0xe6, 0xb7, 0x3d, 0x35, 0x58, 0x56, 0xa0, 0xe9, 0xa9, 0x91, 0x0b,
	0x68, 0x1a, 0x64, 0xb7, 0x66, 0x45, 0xa1, 0x48, 0xc7, 0x76, 0x8a, 0x8e, 0xa0, 0x19, 0x10, 0x2e,
	0x87, 0x0c, 0x05, 0xf1, 0x36, 0xb3, 0xb4, 0x2c, 0xf5, 0xee, 0x8e, 0xba, 0x5a, 0x01, 0xdd, 0x4c,
	0x01, 0x5d, 0x27, 0x53, 0x00, 0x46, 0x32, 0x6f, 0xa0, 0xd3, 0x4c, 0xc9, 0x57, 0xd5, 0x1e, 0x08,
	0x0b, 0xd2, 0x84, 0xb6, 0xe0, 0x5d, 0xd5, 0x7e, 0xd3, 0x59, 0x9d, 0x5f, 0xa1, 0x26, 0x6f, 0x71,
	0x12, 0xd3, 0x84, 0x88, 0x28, 0x41, 0x4d, 0xd8, 0xa7, 0x2b, 0xc2, 0x02, 0x75, 0xd5, 0x16, 0xd6,
	0x06, 0xfa, 0x0a, 0x4a, 0x4f, 0x24, 0x08, 0xa8, 0x30, 0x2f, 0xc5, 0x58, 0x1d, 0xac, 0xb3, 0x07,
	0x24, 0x26, 0x1e, 0x13, 0x6b, 0xf4, 0x1d, 0x34, 0x1e, 0x12, 0x4a, 0xdd, 0x39, 0x09, 0xfd, 0x27,
	0xe6, 0x8b, 0xa5, 0x2a, 0x53, 0xc0, 0x75, 0xe9, 0xed, 0x67, 0x4e, 0xf4, 0x35, 0x58, 0x0a, 0xf3,
	0x19, 0x7f, 0x34, 0xef, 0xa4, 0x22, 0x1d, 0xd7, 0x8c, 0x3f, 0x66, 0x13, 0xfd, 0x65, 0xa4, 0xf4,
	0xce, 0x89, 0xee, 0xc0, 0x96, 0xd9, 0xf8, 0x85, 0x44, 0xbf, 0xc8, 0x54, 0xff, 0xe5, 0xb4, 0xde,
	0xee, 0xb4, 0xfc, 0xa4, 0x78, 0x8c, 0x12, 0xcd, 0x5c, 0x99, 0x29, 0xdf, 0xa4, 0x17, 0xad, 0x56,
	0x4c, 0xb8, 0x4b, 0xc2, 0x97, 0x66, 0x3c, 0xd0, 0xae, 0xdf, 0x09, 0x5f, 0xa2, 0x5f, 0xc0, 0xda,
	0xfc, 0xe3, 0xd4, 0xeb, 0xff, 0xfc, 0xad, 0x6d, 0x61, 0xd9, 0x34, 0xa1, 0x01, 0x25, 0x9c, 0x2a,
	0x31, 0x54, 0x70, 0x66, 0x9e, 0x8d, 0xa1, 0xa2, 0x74, 0xbe, 0x8e, 0x29, 0xaa, 0x42, 0x79, 0x38,
	0xbe, 0xeb, 0x8d, 0x86, 0xd7, 0xf6, 0x1e, 0xaa, 0x83, 0x35, 0xeb, 0x39, 0x37, 0xa3, 0xd1, 0xd0,
	0xb9, 0xb1, 0x73, 0x32, 0x36, 0x73, 0x26, 0xb8, 0x77, 0x7b, 0x63, 0xe7, 0x11, 0x40, 0xe9, 0xef,
	0xe9, 0x68, 0x38, 0xfe, 0xd3, 0x2e, 0x48, 0xae, 0x3f, 0x99, 0x38, 0x33, 0x07, 0xf7, 0xa6, 0x76,
	0xf1, 0xec, 0x04, 0xea, 0x3b, 0xff, 0x0d, 0x64, 0x43, 0xcd, 0x19, 0x4c, 0x5d, 0x67, 0x34, 0x73,
	0x6f, 0xf1, 0x74, 0x60, 0xef, 0xf5, 0x8b, 0xf7, 0xf9, 0x78, 0x3e, 0x2f, 0xa9, 0x89, 0x7f, 0xfe,
	0x14, 0x00, 0x00, 0xff, 0xff, 0x42, 0x0f, 0x8e, 0xee, 0xe5, 0x05, 0x00, 0x00,
}
